# 1.0 Using NashPy

In [41]:
import nashpy as nash
import numpy as np

# Payoff matrix for toy example
A = np.array([[0,4],[1,3]]) # A is first digit in overall matrix
B = np.array([[0,1],[4,3]]) # B is second digit in overall matrix
toy = nash.Game(A,B)

print(str(toy)+"\n")

# Finds first Nash with Lemke-Howson
lh = toy.lemke_howson(initial_dropped_label=0)
print(str(lh)+"\n")

# Prints out labels at various stages
equilibria = toy.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

# [1, 0], [0, 1] = top, right
# [0, 1], [1, 0] = bottom, left

Bi matrix game with payoff matrices:

Row player:
[[0 4]
 [1 3]]

Column player:
[[0 1]
 [4 3]]

(array([1., 0.]), array([0., 1.]))

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0., 1.]), array([1., 0.]))
(array([1., 0.]), array([0., 1.]))
